# Generated by Django 5.0.6 on 2024-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('post', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
