# Generated by Django 5.0.6 on 2024-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('following', models.IntegerField()),
                ('followers', models.IntegerField()),
            ],
        ),
    ]
