# Generated by Django 5.0.6 on 2024-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_delete_profile_user_followers_user_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('following_username', models.CharField(max_length=100)),
                ('following_user_id', models.IntegerField()),
            ],
        ),
    ]
